// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// KL_Cox_Estimate_cpp
arma::vec KL_Cox_Estimate_cpp(const arma::mat& Z, const arma::vec& delta, const arma::vec& delta_tilde, const arma::vec& n_each_stratum, const double eta, arma::vec beta_initial, const double tol, const int maxit, const double lambda, bool backtrack, bool message);
RcppExport SEXP _coxkll_KL_Cox_Estimate_cpp(SEXP ZSEXP, SEXP deltaSEXP, SEXP delta_tildeSEXP, SEXP n_each_stratumSEXP, SEXP etaSEXP, SEXP beta_initialSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP lambdaSEXP, SEXP backtrackSEXP, SEXP messageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta_tilde(delta_tildeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    Rcpp::traits::input_parameter< const double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_initial(beta_initialSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type backtrack(backtrackSEXP);
    Rcpp::traits::input_parameter< bool >::type message(messageSEXP);
    rcpp_result_gen = Rcpp::wrap(KL_Cox_Estimate_cpp(Z, delta, delta_tilde, n_each_stratum, eta, beta_initial, tol, maxit, lambda, backtrack, message));
    return rcpp_result_gen;
END_RCPP
}
// KL_Cox_highdim
List KL_Cox_highdim(const arma::mat& Z, const arma::vec& delta, const arma::vec& delta_tilde, const double& eta, const arma::vec& n_each_stratum, arma::vec& beta, const arma::vec& K1, const int& K0, const arma::vec& lambda_seq, const double& alpha, bool lambda_early_stop, double stop_loss_ratio, const arma::vec& group_multiplier, const int& max_total_iter, const int& max_each_iter, const double& tol, const int& initial_active_group, const double& nvar_max, const double& group_max, const bool& trace_lambda, const bool& actSet, const int& actIter, const int& activeGroupNum, const bool& actSetRemove);
RcppExport SEXP _coxkll_KL_Cox_highdim(SEXP ZSEXP, SEXP deltaSEXP, SEXP delta_tildeSEXP, SEXP etaSEXP, SEXP n_each_stratumSEXP, SEXP betaSEXP, SEXP K1SEXP, SEXP K0SEXP, SEXP lambda_seqSEXP, SEXP alphaSEXP, SEXP lambda_early_stopSEXP, SEXP stop_loss_ratioSEXP, SEXP group_multiplierSEXP, SEXP max_total_iterSEXP, SEXP max_each_iterSEXP, SEXP tolSEXP, SEXP initial_active_groupSEXP, SEXP nvar_maxSEXP, SEXP group_maxSEXP, SEXP trace_lambdaSEXP, SEXP actSetSEXP, SEXP actIterSEXP, SEXP activeGroupNumSEXP, SEXP actSetRemoveSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta_tilde(delta_tildeSEXP);
    Rcpp::traits::input_parameter< const double& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type K1(K1SEXP);
    Rcpp::traits::input_parameter< const int& >::type K0(K0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda_seq(lambda_seqSEXP);
    Rcpp::traits::input_parameter< const double& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type lambda_early_stop(lambda_early_stopSEXP);
    Rcpp::traits::input_parameter< double >::type stop_loss_ratio(stop_loss_ratioSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type group_multiplier(group_multiplierSEXP);
    Rcpp::traits::input_parameter< const int& >::type max_total_iter(max_total_iterSEXP);
    Rcpp::traits::input_parameter< const int& >::type max_each_iter(max_each_iterSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int& >::type initial_active_group(initial_active_groupSEXP);
    Rcpp::traits::input_parameter< const double& >::type nvar_max(nvar_maxSEXP);
    Rcpp::traits::input_parameter< const double& >::type group_max(group_maxSEXP);
    Rcpp::traits::input_parameter< const bool& >::type trace_lambda(trace_lambdaSEXP);
    Rcpp::traits::input_parameter< const bool& >::type actSet(actSetSEXP);
    Rcpp::traits::input_parameter< const int& >::type actIter(actIterSEXP);
    Rcpp::traits::input_parameter< const int& >::type activeGroupNum(activeGroupNumSEXP);
    Rcpp::traits::input_parameter< const bool& >::type actSetRemove(actSetRemoveSEXP);
    rcpp_result_gen = Rcpp::wrap(KL_Cox_highdim(Z, delta, delta_tilde, eta, n_each_stratum, beta, K1, K0, lambda_seq, alpha, lambda_early_stop, stop_loss_ratio, group_multiplier, max_total_iter, max_each_iter, tol, initial_active_group, nvar_max, group_max, trace_lambda, actSet, actIter, activeGroupNum, actSetRemove));
    return rcpp_result_gen;
END_RCPP
}
// rev_cumsum
arma::vec rev_cumsum(const arma::vec& X);
RcppExport SEXP _coxkll_rev_cumsum(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(rev_cumsum(X));
    return rcpp_result_gen;
END_RCPP
}
// pl_cal_theta
double pl_cal_theta(const arma::vec& lp, const arma::vec& delta, const arma::vec& n_each_stratum);
RcppExport SEXP _coxkll_pl_cal_theta(SEXP lpSEXP, SEXP deltaSEXP, SEXP n_each_stratumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type lp(lpSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    rcpp_result_gen = Rcpp::wrap(pl_cal_theta(lp, delta, n_each_stratum));
    return rcpp_result_gen;
END_RCPP
}
// calculateDeltaTilde
arma::vec calculateDeltaTilde(const arma::vec& event, const arma::vec& time, const arma::vec& RS, const arma::vec& n_each_stratum);
RcppExport SEXP _coxkll_calculateDeltaTilde(SEXP eventSEXP, SEXP timeSEXP, SEXP RSSEXP, SEXP n_each_stratumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type event(eventSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type RS(RSSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateDeltaTilde(event, time, RS, n_each_stratum));
    return rcpp_result_gen;
END_RCPP
}
// loss_fn_cpp
List loss_fn_cpp(const arma::mat& Z, const arma::vec& delta, arma::vec& beta, const arma::vec& n_each_stratum);
RcppExport SEXP _coxkll_loss_fn_cpp(SEXP ZSEXP, SEXP deltaSEXP, SEXP betaSEXP, SEXP n_each_stratumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    rcpp_result_gen = Rcpp::wrap(loss_fn_cpp(Z, delta, beta, n_each_stratum));
    return rcpp_result_gen;
END_RCPP
}
// ddloglik_S0
List ddloglik_S0(const arma::mat& Z, const arma::vec& delta, const arma::vec& beta, const arma::vec& n_each_stratum);
RcppExport SEXP _coxkll_ddloglik_S0(SEXP ZSEXP, SEXP deltaSEXP, SEXP betaSEXP, SEXP n_each_stratumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    rcpp_result_gen = Rcpp::wrap(ddloglik_S0(Z, delta, beta, n_each_stratum));
    return rcpp_result_gen;
END_RCPP
}
// cox_c_index
Rcpp::List cox_c_index(const arma::vec& time, const arma::vec& xbeta, const arma::vec& delta);
RcppExport SEXP _coxkll_cox_c_index(SEXP timeSEXP, SEXP xbetaSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type xbeta(xbetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(cox_c_index(time, xbeta, delta));
    return rcpp_result_gen;
END_RCPP
}
// maxgrad
double maxgrad(arma::mat& x, arma::vec& r, arma::vec& K, arma::vec& m);
RcppExport SEXP _coxkll_maxgrad(SEXP xSEXP, SEXP rSEXP, SEXP KSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(maxgrad(x, r, K, m));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_coxkll_KL_Cox_Estimate_cpp", (DL_FUNC) &_coxkll_KL_Cox_Estimate_cpp, 11},
    {"_coxkll_KL_Cox_highdim", (DL_FUNC) &_coxkll_KL_Cox_highdim, 24},
    {"_coxkll_rev_cumsum", (DL_FUNC) &_coxkll_rev_cumsum, 1},
    {"_coxkll_pl_cal_theta", (DL_FUNC) &_coxkll_pl_cal_theta, 3},
    {"_coxkll_calculateDeltaTilde", (DL_FUNC) &_coxkll_calculateDeltaTilde, 4},
    {"_coxkll_loss_fn_cpp", (DL_FUNC) &_coxkll_loss_fn_cpp, 4},
    {"_coxkll_ddloglik_S0", (DL_FUNC) &_coxkll_ddloglik_S0, 4},
    {"_coxkll_cox_c_index", (DL_FUNC) &_coxkll_cox_c_index, 3},
    {"_coxkll_maxgrad", (DL_FUNC) &_coxkll_maxgrad, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_coxkll(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
