# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

KL_Cox_Estimate_cpp <- function(Z, delta, delta_tilde, n_each_stratum, eta, beta_initial, tol = 1.0e-7, maxit = 50L, lambda = 0.0, backtrack = FALSE, message = FALSE) {
    .Call(`_survkl_KL_Cox_Estimate_cpp`, Z, delta, delta_tilde, n_each_stratum, eta, beta_initial, tol, maxit, lambda, backtrack, message)
}

KL_Cox_highdim <- function(Z, delta, delta_tilde, eta, n_each_stratum, beta, K1, K0, lambda_seq, alpha, lambda_early_stop, stop_loss_ratio, group_multiplier, max_total_iter, max_each_iter, tol, initial_active_group, nvar_max, group_max, trace_lambda, actSet, actIter, activeGroupNum, actSetRemove) {
    .Call(`_survkl_KL_Cox_highdim`, Z, delta, delta_tilde, eta, n_each_stratum, beta, K1, K0, lambda_seq, alpha, lambda_early_stop, stop_loss_ratio, group_multiplier, max_total_iter, max_each_iter, tol, initial_active_group, nvar_max, group_max, trace_lambda, actSet, actIter, activeGroupNum, actSetRemove)
}

rev_cumsum <- function(X) {
    .Call(`_survkl_rev_cumsum`, X)
}

pl_cal_theta <- function(lp, delta, n_each_stratum) {
    .Call(`_survkl_pl_cal_theta`, lp, delta, n_each_stratum)
}

calculateDeltaTilde <- function(event, time, RS, n_each_stratum) {
    .Call(`_survkl_calculateDeltaTilde`, event, time, RS, n_each_stratum)
}

loss_fn_cpp <- function(Z, delta, beta, n_each_stratum) {
    .Call(`_survkl_loss_fn_cpp`, Z, delta, beta, n_each_stratum)
}

ddloglik_S0 <- function(Z, delta, beta, n_each_stratum) {
    .Call(`_survkl_ddloglik_S0`, Z, delta, beta, n_each_stratum)
}

cox_c_index <- function(time, xbeta, delta) {
    .Call(`_survkl_cox_c_index`, time, xbeta, delta)
}

maxgrad <- function(x, r, K, m) {
    .Call(`_survkl_maxgrad`, x, r, K, m)
}

